### ISSUE TITLE
xubuntu 16.04 설치에러 (./04-deploy-openstack.sh )

### ISSUE THREAD

**Issue by roykang75** [sktelecom-oslab/taco-scripts#12]
일반 사용자입니다.

xubuntu 16.04에서 ./04-deploy-openstack.sh  설치시 에러나 납니다.
로그는 아래와 같습니다.
어떻게 하면 될까요?

```
root@taco-aio:/home/roy/workspace/taco-scripts# ./04-deploy-openstack.sh 
++ ip route get 8.8.8.8
++ awk '/8.8.8.8/ {print $7}'
+ EXIP=10.0.2.15
++ ip route get 8.8.8.8
++ awk '/8.8.8.8/ {print $3}'
+ EXGW=10.0.2.2
++ ip route get 8.8.8.8
++ awk '/8.8.8.8/ {print $5}'
+ EXNIC=enp0s3
++ cat /etc/os-release
++ grep PRETTY_NAME
++ sed s/PRETTY_NAME=//g
++ awk '{print $1}'
++ sed 's/["]//g'
+ OS_DISTRO=Ubuntu
+ '[' Ubuntu == Red ']'
+ '[' Ubuntu == CentOS ']'
+ '[' Ubuntu == Ubuntu ']'
++ awk '/Network:/{print $2}'
++ ipcalc -n 10.0.2.15 10.0.2.2
+ CIDR=10.0.2.0/24
+ ARMADA_MANIFEST_DIR=/root/apps/armada-manifests
+ '[' -d /root/apps/armada-manifests ']'
+ rm -rf /root/apps/armada-manifests
+ cd /root/apps
+ git clone https://github.com/sktelecom-oslab/armada-manifests.git
Cloning into 'armada-manifests'...
remote: Counting objects: 23, done.
remote: Total 23 (delta 0), reused 0 (delta 0), pack-reused 23
Unpacking objects: 100% (23/23), done.
Checking connectivity... done.
+ armada apply /root/apps/armada-manifests/taco-aio-manifest.yaml --set chart:ceph:values.network.public=10.0.2.0/24 --set chart:ceph:values.network.cluster=10.0.2.0/24 --set chart:neutron:values.network.interface.tunnel=enp0s3
2018-02-05 15:43:05.438 2944 INFO armada.handlers.armada [-] Performing Pre-Flight Operations
2018-02-05 15:43:05.460 2944 INFO armada.handlers.armada [-] Cloning repo: https://github.com/sktelecom-oslab/openstack-helm branch: 2.0.0
2018-02-05 15:43:05.461 2944 INFO armada.utils.source [-] Cloning [https://github.com/sktelecom-oslab/openstack-helm]
2018-02-05 15:43:10.590 2944 INFO armada.handlers.armada [-] Deploying: Openstack Infra Services
2018-02-05 15:43:10.803 2944 INFO armada.handlers.chartbuilder [-] Building dependency chart helm-toolkit for release ceph.
2018-02-05 15:43:10.838 2944 INFO armada.handlers.armada [-] Installing release ceph
2018-02-05 15:43:10.844 2944 INFO armada.handlers.tiller [-] Wait: True, Timeout: 3600
2018-02-05 15:43:11.833 2944 CRITICAL armada [-] Unhandled error: armada.exceptions.tiller_exceptions.ReleaseException: Failed to Install release: taco-ceph - Tiller Message: b'Initial install underway'
2018-02-05 15:43:11.833 2944 ERROR armada Traceback (most recent call last):
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/tiller.py", line 347, in install_release
2018-02-05 15:43:11.833 2944 ERROR armada     metadata=self.metadata)
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 492, in __call__
2018-02-05 15:43:11.833 2944 ERROR armada     return _end_unary_response_blocking(state, call, False, deadline)
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
2018-02-05 15:43:11.833 2944 ERROR armada     raise _Rendezvous(state, None, None, deadline)
2018-02-05 15:43:11.833 2944 ERROR armada grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, a release named taco-ceph already exists.
2018-02-05 15:43:11.833 2944 ERROR armada Run: helm ls --all taco-ceph; to check the status of the release
2018-02-05 15:43:11.833 2944 ERROR armada Or run: helm del --purge taco-ceph; to delete it)>
2018-02-05 15:43:11.833 2944 ERROR armada 
2018-02-05 15:43:11.833 2944 ERROR armada During handling of the above exception, another exception occurred:
2018-02-05 15:43:11.833 2944 ERROR armada 
2018-02-05 15:43:11.833 2944 ERROR armada Traceback (most recent call last):
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/bin/armada", line 10, in <module>
2018-02-05 15:43:11.833 2944 ERROR armada     sys.exit(main())
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
2018-02-05 15:43:11.833 2944 ERROR armada     return self.main(*args, **kwargs)
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
2018-02-05 15:43:11.833 2944 ERROR armada     rv = self.invoke(ctx)
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
2018-02-05 15:43:11.833 2944 ERROR armada     return _process_result(sub_ctx.command.invoke(sub_ctx))
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
2018-02-05 15:43:11.833 2944 ERROR armada     return ctx.invoke(self.callback, **ctx.params)
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
2018-02-05 15:43:11.833 2944 ERROR armada     return callback(*args, **kwargs)
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
2018-02-05 15:43:11.833 2944 ERROR armada     return f(get_current_context(), *args, **kwargs)
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/cli/apply.py", line 136, in apply_create
2018-02-05 15:43:11.833 2944 ERROR armada     target_manifest).invoke()
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/cli/apply.py", line 218, in invoke
2018-02-05 15:43:11.833 2944 ERROR armada     resp = armada.sync()
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/armada.py", line 355, in sync
2018-02-05 15:43:11.833 2944 ERROR armada     timeout=chart_timeout)
2018-02-05 15:43:11.833 2944 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/tiller.py", line 350, in install_release
2018-02-05 15:43:11.833 2944 ERROR armada     raise ex.ReleaseException(release, status, 'Install')
2018-02-05 15:43:11.833 2944 ERROR armada armada.exceptions.tiller_exceptions.ReleaseException: Failed to Install release: taco-ceph - Tiller Message: b'Initial install underway'
2018-02-05 15:43:11.833 2944 ERROR armada 
root@taco-aio:/home/roy/workspace/taco-scripts# 
```

**Comment by Jaesang** [comment]
taco-ceph라는 helm package가 중복 설치된 느낌인데요(helm list로 조회가능) 
helm delete --purge taco-ceph를 하시고 그게 정상적으로 완료된 후에 다시 설치해보세요.
04번 스크립트를 설치하기 전에 helm list를 했을 때 아무것도 없어야합니다.

**Comment by roykang75** [comment]
@Jaesang 말씀하신대로 했는데 에러가 나네요. (timeout)
helm list를 실행해서 아무것도 나오지 않는 것 확인하고 04번 스크립트를 실행했습니다.
```
2018-02-05 16:54:50.072 24839 CRITICAL armada [-] Unhandled error: armada.exceptions.tiller_exceptions.ReleaseException: Failed to Install release: taco-ceph - Tiller Message: b'Release "taco-ceph" failed: timed out waiting for the condition'
```

전체 로그입니다.

```
root@taco-aio:/home/roy/workspace/taco-scripts# helm delete --purge taco-ceph
release "taco-ceph" deleted
root@taco-aio:/home/roy/workspace/taco-scripts# helm list
root@taco-aio:/home/roy/workspace/taco-scripts# ./04-deploy-openstack.sh 
++ ip route get 8.8.8.8
++ awk '/8.8.8.8/ {print $7}'
+ EXIP=10.0.2.15
++ ip route get 8.8.8.8
++ awk '/8.8.8.8/ {print $3}'
+ EXGW=10.0.2.2
++ ip route get 8.8.8.8
++ awk '/8.8.8.8/ {print $5}'
+ EXNIC=enp0s3
++ cat /etc/os-release
++ grep PRETTY_NAME
++ awk '{print $1}'
++ sed 's/["]//g'
++ sed s/PRETTY_NAME=//g
+ OS_DISTRO=Ubuntu
+ '[' Ubuntu == Red ']'
+ '[' Ubuntu == CentOS ']'
+ '[' Ubuntu == Ubuntu ']'
++ ipcalc -n 10.0.2.15 10.0.2.2
++ awk '/Network:/{print $2}'
+ CIDR=10.0.2.0/24
+ ARMADA_MANIFEST_DIR=/root/apps/armada-manifests
+ '[' -d /root/apps/armada-manifests ']'
+ rm -rf /root/apps/armada-manifests
+ cd /root/apps
+ git clone https://github.com/sktelecom-oslab/armada-manifests.git
Cloning into 'armada-manifests'...
remote: Counting objects: 23, done.
remote: Total 23 (delta 0), reused 0 (delta 0), pack-reused 23
Unpacking objects: 100% (23/23), done.
Checking connectivity... done.
+ armada apply /root/apps/armada-manifests/taco-aio-manifest.yaml --set chart:ceph:values.network.public=10.0.2.0/24 --set chart:ceph:values.network.cluster=10.0.2.0/24 --set chart:neutron:values.network.interface.tunnel=enp0s3
2018-02-05 15:54:38.883 24839 INFO armada.handlers.armada [-] Performing Pre-Flight Operations
2018-02-05 15:54:38.904 24839 INFO armada.handlers.armada [-] Cloning repo: https://github.com/sktelecom-oslab/openstack-helm branch: 2.0.0
2018-02-05 15:54:38.905 24839 INFO armada.utils.source [-] Cloning [https://github.com/sktelecom-oslab/openstack-helm]
2018-02-05 15:54:46.737 24839 INFO armada.handlers.armada [-] Deploying: Openstack Infra Services
2018-02-05 15:54:46.959 24839 INFO armada.handlers.chartbuilder [-] Building dependency chart helm-toolkit for release ceph.
2018-02-05 15:54:46.985 24839 INFO armada.handlers.armada [-] Installing release ceph
2018-02-05 15:54:46.990 24839 INFO armada.handlers.tiller [-] Wait: True, Timeout: 3600
2018-02-05 16:54:50.072 24839 CRITICAL armada [-] Unhandled error: armada.exceptions.tiller_exceptions.ReleaseException: Failed to Install release: taco-ceph - Tiller Message: b'Release "taco-ceph" failed: timed out waiting for the condition'
2018-02-05 16:54:50.072 24839 ERROR armada Traceback (most recent call last):
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/tiller.py", line 347, in install_release
2018-02-05 16:54:50.072 24839 ERROR armada     metadata=self.metadata)
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 492, in __call__
2018-02-05 16:54:50.072 24839 ERROR armada     return _end_unary_response_blocking(state, call, False, deadline)
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
2018-02-05 16:54:50.072 24839 ERROR armada     raise _Rendezvous(state, None, None, deadline)
2018-02-05 16:54:50.072 24839 ERROR armada grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, release taco-ceph failed: timed out waiting for the condition)>
2018-02-05 16:54:50.072 24839 ERROR armada 
2018-02-05 16:54:50.072 24839 ERROR armada During handling of the above exception, another exception occurred:
2018-02-05 16:54:50.072 24839 ERROR armada 
2018-02-05 16:54:50.072 24839 ERROR armada Traceback (most recent call last):
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/bin/armada", line 10, in <module>
2018-02-05 16:54:50.072 24839 ERROR armada     sys.exit(main())
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
2018-02-05 16:54:50.072 24839 ERROR armada     return self.main(*args, **kwargs)
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
2018-02-05 16:54:50.072 24839 ERROR armada     rv = self.invoke(ctx)
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
2018-02-05 16:54:50.072 24839 ERROR armada     return _process_result(sub_ctx.command.invoke(sub_ctx))
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
2018-02-05 16:54:50.072 24839 ERROR armada     return ctx.invoke(self.callback, **ctx.params)
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
2018-02-05 16:54:50.072 24839 ERROR armada     return callback(*args, **kwargs)
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
2018-02-05 16:54:50.072 24839 ERROR armada     return f(get_current_context(), *args, **kwargs)
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/cli/apply.py", line 136, in apply_create
2018-02-05 16:54:50.072 24839 ERROR armada     target_manifest).invoke()
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/cli/apply.py", line 218, in invoke
2018-02-05 16:54:50.072 24839 ERROR armada     resp = armada.sync()
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/armada.py", line 355, in sync
2018-02-05 16:54:50.072 24839 ERROR armada     timeout=chart_timeout)
2018-02-05 16:54:50.072 24839 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/tiller.py", line 350, in install_release
2018-02-05 16:54:50.072 24839 ERROR armada     raise ex.ReleaseException(release, status, 'Install')
2018-02-05 16:54:50.072 24839 ERROR armada armada.exceptions.tiller_exceptions.ReleaseException: Failed to Install release: taco-ceph - Tiller Message: b'Release "taco-ceph" failed: timed out waiting for the condition'
2018-02-05 16:54:50.072 24839 ERROR armada 
```

**Comment by powerds** [comment]
저희가 아직 cleanup script를 제공하지 않아서 중간에 다시 시작하는게 쉽지 않네요.

일단 helm list에 아무것도 없다면
kubectl delete ns ceph
위의 명령어로 ceph namespace를 지워주시고, /var/lib/openstack-helm/ceph 디렉토리를 지운 후 다시 시작해 보시길 바랍니다.

**Comment by bluejayA** [comment]
현재는 문제가 없을 것으로 보고 Close 합니다.
