### ISSUE TITLE
armada apply failed. ERROR armada.cli

### ISSUE THREAD

**Issue by javarchoo** [sktelecom-oslab/taco-scripts#16]
When run ./04-deploy-openstack.sh on CentOS 7.4, below error occurs:

`+ armada apply /root/apps/armada-manifests/taco-aio-manifest.yaml --set chart:ceph:values.network.public=192.168.54.0/24 --set chart:ceph:values.network.cluster=192.168.54.0/24 --set chart:neutron:values.network.interface.tunnel=ens33
2018-03-08 15:14:51.793 95469 INFO armada.handlers.armada [-] Performing Pre-Flight Operations
2018-03-08 15:14:52.808 95469 ERROR armada.cli [-] Caught unexpected exception: grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 10.96.0.1:443: getsockopt: no route to host)>
2018-03-08 15:14:52.808 95469 ERROR armada.cli Traceback (most recent call last):
2018-03-08 15:14:52.808 95469 ERROR armada.cli   File "/usr/lib/python3.6/site-packages/armada/cli/__init__.py", line 40, in safe_invoke
2018-03-08 15:14:52.808 95469 ERROR armada.cli     self.invoke()
2018-03-08 15:14:52.808 95469 ERROR armada.cli   File "/usr/lib/python3.6/site-packages/armada/cli/apply.py", line 221, in invoke
2018-03-08 15:14:52.808 95469 ERROR armada.cli     resp = armada.sync()
2018-03-08 15:14:52.808 95469 ERROR armada.cli   File "/usr/lib/python3.6/site-packages/armada/handlers/armada.py", line 233, in sync
2018-03-08 15:14:52.808 95469 ERROR armada.cli     self.pre_flight_ops()
2018-03-08 15:14:52.808 95469 ERROR armada.cli   File "/usr/lib/python3.6/site-packages/armada/handlers/armada.py", line 135, in pre_flight_ops
2018-03-08 15:14:52.808 95469 ERROR armada.cli     failed_releases = self.get_releases_by_status(const.STATUS_FAILED)
2018-03-08 15:14:52.808 95469 ERROR armada.cli   File "/usr/lib/python3.6/site-packages/armada/handlers/armada.py", line 216, in get_releases_by_status
2018-03-08 15:14:52.808 95469 ERROR armada.cli     known_releases = self.tiller.list_charts()
2018-03-08 15:14:52.808 95469 ERROR armada.cli   File "/usr/lib/python3.6/site-packages/armada/handlers/tiller.py", line 258, in list_charts
2018-03-08 15:14:52.808 95469 ERROR armada.cli     for latest_release in self.list_releases():
2018-03-08 15:14:52.808 95469 ERROR armada.cli   File "/usr/lib/python3.6/site-packages/armada/handlers/tiller.py", line 161, in list_releases
2018-03-08 15:14:52.808 95469 ERROR armada.cli     for y in release_list:
2018-03-08 15:14:52.808 95469 ERROR armada.cli   File "/usr/lib64/python3.6/site-packages/grpc/_channel.py", line 348, in __next__
2018-03-08 15:14:52.808 95469 ERROR armada.cli     return self._next()
2018-03-08 15:14:52.808 95469 ERROR armada.cli   File "/usr/lib64/python3.6/site-packages/grpc/_channel.py", line 342, in _next
2018-03-08 15:14:52.808 95469 ERROR armada.cli     raise self
2018-03-08 15:14:52.808 95469 ERROR armada.cli grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 10.96.0.1:443: getsockopt: no route to host)>
2018-03-08 15:14:52.808 95469 ERROR armada.cli`

**Comment by javarchoo** [comment]
solv:
checking nc -v 10.96.0.1 443 on host is ok, but armada.cli can not access to 10.96.0.1:443
when stop firewalld.services, it passed!
